export const data = JSON.parse("{\"key\":\"v-21fa060e\",\"path\":\"/posts/%E4%B8%AA%E4%BA%BA%E5%AD%A6%E4%B9%A0/%E5%B7%A5%E5%85%B7%E5%AD%A6%E4%B9%A0/git.html\",\"title\":\"git-基本使用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"git-基本使用\",\"date\":\"2023-03-21T00:00:00.000Z\",\"category\":[\"git\"],\"summary\":\"黑马2022资料阶段一：java基础-第六章 6-1Git介绍 01-为什么使用代码版本控制系统 代码不仅要本地备份，还要云端备份。可以回滚，回到之前版本。协同工作。明确代码的提交人、提交时间。 02-Git和SVN对比 SVN是集中式版本控制系统，版本库是集中放在中央服务器的，而开发人员工作的时候，用 的都是自己的电脑， 所以首先要从中央服务器下载最新的版\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.iocaop.com/posts/%E4%B8%AA%E4%BA%BA%E5%AD%A6%E4%B9%A0/%E5%B7%A5%E5%85%B7%E5%AD%A6%E4%B9%A0/git.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"赖卓成的笔记\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"git-基本使用\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-03-21T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"6-1Git介绍\",\"slug\":\"_6-1git介绍\",\"link\":\"#_6-1git介绍\",\"children\":[{\"level\":3,\"title\":\"01-为什么使用代码版本控制系统\",\"slug\":\"_01-为什么使用代码版本控制系统\",\"link\":\"#_01-为什么使用代码版本控制系统\",\"children\":[]},{\"level\":3,\"title\":\"02-Git和SVN对比\",\"slug\":\"_02-git和svn对比\",\"link\":\"#_02-git和svn对比\",\"children\":[]}]},{\"level\":2,\"title\":\"6-2Git基操\",\"slug\":\"_6-2git基操\",\"link\":\"#_6-2git基操\",\"children\":[{\"level\":3,\"title\":\"05-Git本地仓库基本工作流程\",\"slug\":\"_05-git本地仓库基本工作流程\",\"link\":\"#_05-git本地仓库基本工作流程\",\"children\":[]},{\"level\":3,\"title\":\"06-Git常用命令\",\"slug\":\"_06-git常用命令\",\"link\":\"#_06-git常用命令\",\"children\":[]},{\"level\":3,\"title\":\"08-Git历史版本管理\",\"slug\":\"_08-git历史版本管理\",\"link\":\"#_08-git历史版本管理\",\"children\":[]},{\"level\":3,\"title\":\"09-分支管理介绍\",\"slug\":\"_09-分支管理介绍\",\"link\":\"#_09-分支管理介绍\",\"children\":[]},{\"level\":3,\"title\":\"10-分支工作流程\",\"slug\":\"_10-分支工作流程\",\"link\":\"#_10-分支工作流程\",\"children\":[]},{\"level\":3,\"title\":\"11-创建和切换分支\",\"slug\":\"_11-创建和切换分支\",\"link\":\"#_11-创建和切换分支\",\"children\":[]},{\"level\":3,\"title\":\"12-合并和删除分支\",\"slug\":\"_12-合并和删除分支\",\"link\":\"#_12-合并和删除分支\",\"children\":[]},{\"level\":3,\"title\":\"13-远程仓库的工作流程\",\"slug\":\"_13-远程仓库的工作流程\",\"link\":\"#_13-远程仓库的工作流程\",\"children\":[]},{\"level\":3,\"title\":\"15-ssh公钥配置\",\"slug\":\"_15-ssh公钥配置\",\"link\":\"#_15-ssh公钥配置\",\"children\":[]},{\"level\":3,\"title\":\"16-代码冲突\",\"slug\":\"_16-代码冲突\",\"link\":\"#_16-代码冲突\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.57,\"words\":1971},\"filePathRelative\":\"posts/个人学习/工具学习/git.md\",\"localizedDate\":\"2023年3月21日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
