name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run docs:build
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: 150.158.20.104
        username: root
        password: qq1111.1
        source: '../../vuepress-blog/.vuepress/dist'
        target: '/usr/local/nginx/html'
