name: Deploy VuePress to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run docs:build
      - name: Deploy to Nginx
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 150.158.20.104
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './dist/'
          target: '/usr/share/nginx/html'
