name: 同步到我的服务器
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run docs:build
    - name: Initialize destination Git repository
      run: |
        cd vuepress-blog/.vuepress/dist
        ls
        git config --global user.email "911823616@qq.com"
        git config --global user.name "赖卓成"
        git remote add origin https://lzcxfz:${{ secrets.GIT_PASSWORD }}@github.com/lzcxfz/webserver.git
    - name: Add and commit files
      run: |
        git add .
        git commit -m "Deploy build files"
    - name: Push to destination Git repository
      run: |
        git push origin main